import { Toaster } from '@/components/ui/toaster'
import { UserProvider } from '@/context/UserContext'
import type { Metadata } from 'next'
import { Lexend } from 'next/font/google'
import './globals.css'

const lexend = Lexend({
	subsets: ['latin'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={lexend.className}>
				<div className='wrapper'>
					<UserProvider>{children}</UserProvider>
					<Toaster />
				</div>
			</body>
		</html>
	)
}
